name: Build

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!develop'

jobs:
  build:
    name: working
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: ci_post_clone
        run: |
          defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json)
          echo "$scheme_list"
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default

      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: 'macOS'
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ -d "$PWD/$scheme.xcodeproj" ]; then filetype_parameter="project" && file_to_build="$scheme.xcodeproj"; elif [ -d "$PWD/$scheme.xcworkspace" ]; then filetype_parameter="workspace" && file_to_build="$scheme.xcworkspace"; else echo "ERROR: Xcode project or workspace not found."; exit 1; fi
          xcodebuild build -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -configuration Release